name: recsys_env
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - seaborn
  - pip:
      - torchrec
